### ISSUE TITLE
Allow other file format(s) for structure file input

### ISSUE THREAD

**Issue by rlavendomme** [jmaglic/ballpit#13]
Currently, only .xyz file format can be read for the structure.
While this is a simple and convenient file format for isolated structures, it is necessary to allow crystallographic structure files as input for future features of the program.

.cif files can be extremely complicated to read as the coordinates are based on the unit cell parameters (instead of cartesian coordinates in angtröm) and only a portion of the atoms are localized if there are symmetry elements (the other atoms are implied based on the symmetry).

.pbd files are much simpler to read (see format at http://www.wwpdb.org/documentation/file-format ):
We only need to read the line starting with CRYST1 for the unit cell parameters and the lines starting with ATOM or HETATM for the atom coordinates.
If we allow the .pdb file format as an input, we need to add two options (boxes to tick):
1) ask if HETATM should be read or not. Often, for proteins, the HETATM (such as solvent molecules) should not be taken into account for the calculation. For non biomolecules however, it is likely that all important atoms will be labeled HETATM. Thus this option is crucial.
2) ask if the program should consider simply the isolated molecule (same atom mapping as with .xyz files) or the crystal structure. In the latter case, the program would need to generate the neighboring unit cells at least in part for the atom mapping to make sure that there won't be artificial empty space accessible by probes. Yet, the voxels should only fill the main unit cell.

**Comment by rlavendomme** [comment]
I just came across different formats of .xyz files for chemical structures. The ones generated from Mercury (XMol file .xyz) and the ones generated from Chem3D (Tinker input file .xyz) are different. There might be more formats that I am unaware of.

isobutane XMol.xyz generated via Mercury:
``` 14
    1  C   -7.945000   -0.100000   -0.336000    1    2    3    4    5
    2  C   -9.269000   -0.881000   -0.362000    1    1    6    7    8
    3  C   -8.208000    1.414000   -0.366000    1    1    9   10   11
    4  C   -7.114000   -0.482000    0.899000    1    1   12   13   14
    5  H   -7.359000   -0.372000   -1.251000    5    1
    6  H   -9.892000   -0.646000    0.530000    5    2
    7  H   -9.865000   -0.632000   -1.270000    5    2
    8  H   -9.087000   -1.980000   -0.371000    5    2
    9  H   -7.253000    1.988000   -0.377000    5    3
   10  H   -8.784000    1.705000   -1.274000    5    3
   11  H   -8.790000    1.739000    0.526000    5    3
   12  H   -6.139000    0.057000    0.911000    5    4
   13  H   -6.893000   -1.574000    0.913000    5    4
   14  H   -7.654000   -0.231000    1.840000    5    4
```
isobutane Tinker.xyz generated via Chem3D:
``` 14
    1  C   -7.945000   -0.100000   -0.336000    1    2    3    4    5
    2  C   -9.269000   -0.881000   -0.362000    1    1    6    7    8
    3  C   -8.208000    1.414000   -0.366000    1    1    9   10   11
    4  C   -7.114000   -0.482000    0.899000    1    1   12   13   14
    5  H   -7.359000   -0.372000   -1.251000    5    1
    6  H   -9.892000   -0.646000    0.530000    5    2
    7  H   -9.865000   -0.632000   -1.270000    5    2
    8  H   -9.087000   -1.980000   -0.371000    5    2
    9  H   -7.253000    1.988000   -0.377000    5    3
   10  H   -8.784000    1.705000   -1.274000    5    3
   11  H   -8.790000    1.739000    0.526000    5    3
   12  H   -6.139000    0.057000    0.911000    5    4
   13  H   -6.893000   -1.574000    0.913000    5    4
   14  H   -7.654000   -0.231000    1.840000    5    4
```

We should make sure that the future user manual prevent any possible confusion and probably keep working with XMol files since they can be generated from the freely available Mercury software (as opposed to the paid Chem3D software).

**Comment by jmaglic** [comment]
It seems like we will have to look into a lot of exception cases, since xyz files are not standardised. I agree that as least for now it's best to focus on a single case, and just keep in mind that we may need to expand the code down the line.

**Comment by rlavendomme** [comment]
I am planning to include .pdb as an accepted structure input file format and add two options.
The way I picture is would be like that in the browser panel: 
![browse pannel](https://user-images.githubusercontent.com/65511614/90399679-a3bf5700-e09b-11ea-9540-b45753d0321e.png)

The pdb file reading will natively only focus on ATOM lines and store for coordinates and element symbols according to the official file format ( http://www.wwpdb.org/documentation/file-format ). Then the rest of the program will handle the data similarly to how it is working with the .xyz file.
The user can choose to include HETATM lines as well.
The last option will be the most complicated to add. I intend to allow the user to choose to analyze not only an isolated structure but the full unit cell. Indeed, it is sometimes interesting to analyze the cavities within a crystal rather than within a molecule. So even for molecules with no inner cavities, there can be cavities between the molecules in the crystal.
For this, the program will have to read the crystallographic information from the pdb file, generate the atoms from symmetry elements and neighboring unit cells, then analyze voxels only within the main unit cells (even if there are atoms are outside).
So this option will modify some aspects of the calculations in the back-end and will require to hard code all the symmetry elements for each space group.

Is there any suggestion before I work on this task?

**Comment by jmaglic** [comment]
Intuitively, it seems to me that it's better to use config files rather than hardcode large amounts of information into the code. Maybe that's what you mean though.

I recommend you begin working on the .pdb import by writing methods that obtain the information you'd get from an .xyz file. What I mean is that the result from the .pbd import should be the same as the result from the .xyz import. Then make a pull request for me to review. Smaller changes will make life easier for me.

Afterwards I suggest working on the GUI. A few points though:
- Why do we need a checkbox, for the user to select between filetypes? It's quite trivial for the program to determine whether it's receiving a .xyz or a .pdb file.
- What does including HETATM lines do? What are HETATM lines?
- I think the space you have carved out for these options should be exclusively for import options. Having the options to include HETATM lines in there makes sense to me. However, the option whether to analyse the crystal unit cell should, imo, be in the parameter panel, meaning the panel where the calculation options are. The structuring of the GUI makes sense at the moment, with the import being devoted completely to the left side and the calculation being devoted completely to the right.

As for the last point, I think we can tackle that, once I've implemented the cavity volume algorithm. I will keep the intermolecular cavities in mind.

**Comment by rlavendomme** [comment]
> Intuitively, it seems to me that it's better to use config files rather than hardcode large amounts of information into the code. Maybe that's what you mean though.

I am hesitating between the two options. The point is that space groups are absolute mathematical concepts (contrary to element radii that are measured in different ways), so I would prefer that this information is not stored in an external file in order to prevent users from messing with the file and the definitions of the space groups.
I am not strongly vouching for one solution over another. I am simply stating the results of me overthinking about what could go wrong.
It could be a good idea to directly ask a crystallographer about their opinion on the question.

> I recommend you begin working on the .pdb import by writing methods that obtain the information you'd get from an .xyz file. What I mean is that the result from the .pbd import should be the same as the result from the .xyz import. Then make a pull request for me to review. Smaller changes will make life easier for me.

This part should be easy. I'll work on that asap.

>     * Why do we need a checkbox, for the user to select between filetypes? It's quite trivial for the program to determine whether it's receiving a .xyz or a .pdb file.

The radio button (not exactly a checkbox) only serves to enable or disable the HETATM and unit cell check boxes. Indeed, these options are only meaningful for pdb files. We could also simply write "Options for pdb files" and the user will have to determine what file he is loading and if the options are compatible.

>     * What does including HETATM lines do? What are HETATM lines?

I thought you saw the first message of this issue. I already described what do HETATM do. Basically they stand for hetero atoms (not in the usual sense in organic chemistry) which are atoms not belonging to the biomolecule (more specifically protein). For example a protein crystal structure can have solvent molecules or other small molecules in the unit cell and their atoms will be flagged as HETATM in pdb files to differentiate from the protein itself which is the main thing the biochemist wants to study. It simplifies the analysis of the crystal structures of proteins in softwares.
However, since the program developed here is not only designed for biomolecules, the structures in the pdb files loaded by users could have only HETATM flagged atoms. Therefore, we need to allow the reading of either only ATOM, or both ATOM and HETATM (I don't think that there is a reason to allow for the reading of only HETATM so I am not planning to add such an option).

>     * I think the space you have carved out for these options should be exclusively for import options. Having the options to include HETATM lines in there makes sense to me. However, the option whether to analyse the crystal unit cell should, imo, be in the parameter panel, meaning the panel where the calculation options are. The structuring of the GUI makes sense at the moment, with the import being devoted completely to the left side and the calculation being devoted completely to the right.

I agree to some extent. My point here is that these two options (HETATM and unit cell) are both linked to the type of file in input while all other parameters from the parameter panel apply to both xyz and pdb files.
If we only put the option HETATM in the browser panel and the unit cell option in the parameter panel, it will be necessary to repeat for each "Option for pdb files" or something along this line.

> As for the last point, I think we can tackle that, once I've implemented the cavity volume algorithm. I will keep the intermolecular cavities in mind.

Yes, this part can be added at a later stage. I don't know exactly how the cavity volume algorithm will look like but if you are planning on working only on the single-probe mode for now, you might want to prepare the code so it is easier to implement the 2-probes mode.
