### ISSUE TITLE
isAtomLine for xyz structures not working perfectly

### ISSUE THREAD

**Issue by rlavendomme** [jmaglic/ballpit#16]
```c++
bool isAtomLine(const std::vector<std::string>& substrings) {
  for (char i=1; i<4; i++){
    // using a try-block feels hacky, but the alternative using strtod does as well
    try {
      std::stod(substrings[i]);
    }
    catch (const std::invalid_argument& ia) {
      return false;
    }
  }
  return true;
}
```
There are at least two cases of invalid atom lines that are checked as valid with this function:
1) When the element substring doesn't start with a letter, the line is still considered true.
For example, a line of four numbers is considered true.
2) When one of the coordinates starts with a valid number characters but contains invalid characters. "stod" function checks the character until it reaches an invalid one and keeps everything before the invalid character.
So the line
Ca 5x 6y 7z
is considered valid while it shouldn't.
Yet, letters should not all be excluded since 5e10, for example, is a valid number.

For the first case, it is quite simple to fix it, I propose
```c++
bool isAtomLine(const std::vector<std::string>& substrings) {
  if (isalpha(substrings[0][0])){
    for (char i=1; i<4; i++){
      // using a try-block feels hacky, but the alternative using strtod does as well
      try {
        std::stod(substrings[i]);
      }
      catch (const std::invalid_argument& ia) {
        return false;
      }
    }
    return true;
  }
  else {
  	return false;
  }
}
```

For the second issue, we might need a function to check the whole substrings of coordinates are valid numbers formats.

**Comment by jmaglic** [comment]
> When the element substring doesn't start with a letter, the line is still considered true.
For example, a line of four numbers is considered true.

So what? Why shouldn't the user have the choice to call a custom element "%dummy", but "dummy%" is allowed? I mean why is the condition for a valid atom symbol specifically that it has to start with an alpha numerical character?

> So the line
Ca 5x 6y 7z
is considered valid while it shouldn't.

Ok, but is there a real world example of an input file where this could happen? I feel like the function is fine for all real cases, where the user doesn't purposefully try to break the program.

**Comment by rlavendomme** [comment]
As I wrote, if you don't require a letter in the first substring, a random comment line generated by a software with 4 numbers will be valid and give an element with no symbol and a coordinate.
54 53 96 41 will be valid, which is wrong.
Many softwares generate xyz files differently so it is better to limit potential issues in my opinion.
Regarding your example of %dummy compared to dummy%. Can we agree that, by convention, element symbols will always start with a letter (which is consistent with the function toValidSymbol)?

I hope no user would try to purposely break the program (even if it is a possibility), yet, they might make mistake when generating xyz files (from custom models for example). If there is a line with a wrong coordinate, they wouldn't notice and proceed with a wrongly positioned atom which might lead to undesired outputs.
If the lines ares properly checked, the user will be informed that, for example, out of 10 H atoms he added in his structures, only 9 are recognized. This should prompt the user to investigate his input file.

**Comment by jmaglic** [comment]
> 54 53 96 41 will be valid, which is wrong.

True, but then won't this show up in the new radius panel as an atom with element symbol "54"? Since it will lack a radius, it will be ignored by default. So even if it is incorrectly read, the user will be informed, and even if they miss it, there won't be an influence on their calculation.

In regards to the isAtomLine() function: I played around with std::stod() and now I understand the issue. std::stod() seems very lenient on what string can be converted, which is kind of an issue for our purposes. I'll assign this issue to myself and look for a way to solve it.

**Comment by rlavendomme** [comment]
> True, but then won't this show up in the new radius panel as an atom with element symbol "54"?

True for now since your function "strToValidSymbol" does not erase non letter characters but I intend to modify this function.
Indeed, Pd2+ would be registered as Pd2+ instead of Pd which prevents the retrieval of the radius from the definition file.

I intend to modify this function as
`// reads a string and converts it to valid atom symbol: first character uppercase followed by lowercase characters
std::string strToValidSymbol(std::string str){
  // iterate over all characters in string
  for (int i = 0; i<str.size(); i++) {
  	if (isalpha(str[i])){
      // only for first character in sequence, convert to uppercase
      if (i==0) {
        str[i] = toupper(str[i]);
      }
      // for all other characters, convert to lowercase
      else {
        str[i] = tolower(str[i]);
      }
    }
    else { // Remove number or charges from atoms so that "Pd2+" becomes "Pd"
      str.erase(i, str.size());
    }
  }
  return str;
}`

Which means that the line 54 53 96 41 will show an atom line with no element making it difficult to understand what it is.

**Comment by jmaglic** [comment]
So you want to treat Pd2+ the same as Pd then? Don't ions generally have radii different to their corresponding neutral atom?

**Comment by rlavendomme** [comment]
> So you want to treat Pd2+ the same as Pd then? Don't ions generally have radii different to their corresponding neutral atom?

Yes, they do have different radii considered as ionic radii instead of vdw radii. Now, if the user doesn't know the ionic radius (there are many different definitions), they usually use the vdw radius which is implemented in the software.
We will provide them with means to change manually the radius if they wish to but I expect it will be better to provide a default value.
If they wish to differentiate Pd from Pd2+ within a same structure, I would suggest in the user manual to name the ions differently like Pdion.

This can be discussed at a later stage with potential users (mainly crystallographers and computational chemists).

**Comment by jmaglic** [comment]
I feel like we've strayed far from the original issue. I think we should open a new issue to discuss what the default case should be and to what options the user should be limited. For now I think it's best to implement a robust base case that can be expanded later.

I'm leaving this issue open until I fix the issue.
