### ISSUE TITLE
GUI elements disappearing on files reload

### ISSUE THREAD

**Issue by rlavendomme** [jmaglic/ballpit#20]
After implementing the atom list grid in the GUI and moving the SetSizer in a dedicated function (which is called after each loading of input files), I noticed that elements of the GUI are changing or disappearing when I reload the same files (see picture).
![image](https://user-images.githubusercontent.com/65511614/90203050-d9381c00-dddf-11ea-97db-eb4ff3ca93b8.png)

Loading a new structure file that changes the atom list grid sets back everything to normal in the GUI then, if I reload the new structure file, the same issue arises.

Not sure what is the cause of this issue or even if it happens on other PC or OS. Is it the numerous SetSizer calls that lead to such a strange behavior or something else???

**Comment by jmaglic** [comment]
GUI development is really annoying.

**Comment by rlavendomme** [comment]
I suppose this solution will do for now. The only potential issue will be for later uses with screens of much different resolutions such as when 4k, 8k, ... become the norm. Indeed, the fixed size is pixel-based.
