### ISSUE TITLE
Atom list uses Times New Roman for headers

### ISSUE THREAD

**Issue by jmaglic** [jmaglic/ballpit#23]
The header font of the recently introduced atom list defaults to TimesNewRoman on macOS. When running the program the following message is output in the console:

`CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].`

**Comment by rlavendomme** [comment]
That's surprising for such a simple feature of wxWidget which is supposedly compatible with different OS.
Since we didn't specify a font, it might be the normal behavior for wxGrid usage on macOS.

**Comment by jmaglic** [comment]
Fixed, likely by migrating to wxWidgets 3.1.
