### ISSUE TITLE
Filesystem header not very portable

### ISSUE THREAD

**Issue by rlavendomme** [jmaglic/ballpit#30]
The recent commit bc5b562 and the ones before introduced functions from the header filesystem and filesystem namespace.

Unfortunately, filesystem header and namespace are not compatible with gcc 8 on windows (and that's what I am using). I tested the program while temporarily removing all the filesystem lines and it worked fine. I added them back for now in the include-pdb-input branch I was working on.

I will have to see if I can move to gcc 9 which seems to support filesystem on windows. Otherwise, we might have a problem with portability of the program.

It's already the second OS compatibility problem we have (see issue #27 ).
We should probably see how to limit such problems in the future as it causes unnecessary loss of time to find workarounds (which could end up being to revert back to previous compatible code). So before introducing new headers, library dependencies, etc, I would suggest to check whether they are fully compatible with Windows 10 (+7 ideally), Linux and macOSX.

**Comment by jmaglic** [comment]
I agree. I did actually check whether filesystem was compatible and I found conflicting information. [Articles like this(https://www.codingame.com/playgrounds/5659/c17-filesystem) say:
> With C++17 there’s a nice improvement: for example, we now have the standard filesystem!

So I just decided to try it, I figured you'd tell me if it didn't work. In regards to this issue the fix is pretty simple. It's possible to sacrifice some security by simply using std::strings for the path comparison, and leaving out the check for changed files. In that case, there would be an issue if the user decided to change the file and start the calculations without reimporting the files manually. That's a pretty minor issue though.

The website I linked writes:

>Depending on the version of your compiler you might need to use std::experimental::filesystem namespace.
>- GCC: You have to specify -lstdc++fs when you want filesystem. Implemented in <experimental/filesystem>.

Do you want to try that?

> It's already the second OS compatibility problem we have

I would exchange the "already" with "only". Honestly, designing a program that works cross-platform is no easy task and we likely will have to handle some work arounds unless we want to severely limit the features.

**Comment by rlavendomme** [comment]
> So I just decided to try it, I figured you'd tell me if it didn't work. In regards to this issue the fix is pretty simple. It's possible to sacrifice some security by simply using std::strings for the path comparison, and leaving out the check for changed files. In that case, there would be an issue if the user decided to change the file and start the calculations without reimporting the files manually. That's a pretty minor issue though.

I would go for that solution. The file change while running the program and not reimporting is just an extreme case scenario involving very bad computer practice.

> The website I linked writes:
> 
> > Depending on the version of your compiler you might need to use std::experimental::filesystem namespace.
> > 
> > * GCC: You have to specify -lstdc++fs when you want filesystem. Implemented in <experimental/filesystem>.
> 
> Do you want to try that?

I tried briefly, didn't work. My compiler (gcc 8 on windows 10) didn't even find experimental/filesystem header.

> > It's already the second OS compatibility problem we have
> 
> I would exchange the "already" with "only". Honestly, designing a program that works cross-platform is no easy task and we likely will have to handle some work arounds unless we want to severely limit the features.

I agree that two is not many but it would be better if we can limit future incompatibilities as much as possible in "working" builds. (since I found these incompatibilities in the master branch while previous versions were fully compatible)

**Comment by jmaglic** [comment]
Apparently C++20 will include a portable filesystem. Maybe this solve this issue?

> > So I just decided to try it, I figured you'd tell me if it didn't work. In regards to this issue the fix is pretty simple. It's possible to sacrifice some security by simply using std::strings for the path comparison, and leaving out the check for changed files. In that case, there would be an issue if the user decided to change the file and start the calculations without reimporting the files manually. That's a pretty minor issue though.
> 
> I would go for that solution. The file change while running the program and not reimporting is just an extreme case scenario involving very bad computer practice.

Alright, I'll change it then.

**Comment by rlavendomme** [comment]
So, I tested with the newer version of gcc 9.2 which supports filesystem on windows.
While filesystem functionalities were recognized and didn't cause any error when compiling with the flag -std=c++17 (required for filesystem header in gcc 9.2), new compilation errors arose.
It seems that wxWidgets 3.0.5 that we are using has compatibility issues when using the flag -std=c++17.

Thus, we would need to either 
(i) tweak wxWidgets 3.0.5, 
(ii) move to a newer version of wxWidgets if one version fixes this issue (didn't check), or 
(iii) simply forget about filesystem functionalities and remove the flag -std=c++17 for compilation.

I vote for solution 3 which will make everything simpler and more portable.

**Comment by jmaglic** [comment]
Why do you need to compile wxWidgets with the `-std=C++17` flag? Have you tried compiling it with the `-std=C++11` flag, but then compiling our software with the `-std=C++17` flag?

**Comment by rlavendomme** [comment]
> PS: I haven't tested solution (ii):
> 
> > (ii) move to a newer version of wxWidgets if one version fixes this issue (didn't check)
> 
> It might be simple to try if there is no compatibility issue with the wxWidgets features we already implemented in our program.
> Since we only used very simple features, I suppose we could move to a newer version.

I have now tested the newest version of wxWidgets: https://www.wxwidgets.org/news/2020/07/wxwidgets-3.1.4-released/
Our code is almost compatible with wxWidgets 3.1.4 (only had few errors easily fixed, see detail below). Some new dependencies require to link more libs.
The errors mainly concern
1) the function `SetCellValue` which went from `SetCellValue(value, row, column)` to `SetCellValue(row, column, value)`
2) adding sizers to `wxBoxSizer(wxHORIZONTAL)`. The `wxALIGN_RIGHT` flag becomes unnecessary because the last sizer will be on the right anyway so there is an error during run time. (we only had three such occurrences in our code, so easily fixed)

And most importantly, the flag `-std=c++17` works on windows 10. I could build wxWidgets libraries with this flag and then compile our program code with it. The header `<filesystem>` is also compatible.

Now, the obvious solution would be to move to wxWidgets 3.1.4 but before doing so, we need to consider few points:
1) wxWidgets 3.1.x is not yet the official latest stable version. It is still officially version 3.0.x
2) I checked everything on windows 10 but we need to make sure that everything runs smoothly on macOSX and linux.

So @jmaglic and @BSVogler , I'll make a branch for my stable code running with wxWidgets 3.1.4, before going any further for anything else, could you try to build wxWidgets 3.1.4 on your side and compile the code from this branch, please?

**Comment by BSVogler** [comment]
Can we not just rely on the wxwidget binaries? I did not compile wxwidgets myself and only installed the binaries via brew. The binaries are provided on the [download section](https://www.wxwidgets.org/downloads/).

**Comment by rlavendomme** [comment]
> 
> 
> Can we not just rely on the wxwidget binaries? I did not compile wxwidgets myself and only installed the binaries via brew. The binaries are provided on the [download section](https://www.wxwidgets.org/downloads/).

I didn't try myself but from what I read, it was always recommended to build wxWidgets on your system to make sure that everything would work properly. Another issue with pre-build binaries is that your program will need them and won't run if you don't have them on the system (such as a random user):
> Please note that during run-time the executables will require wxWidgets DLLs in addition to MSVC run-time DLLs, so you should consider adding the directory containing these DLLs to your PATH and either distributing them with your application or instructing your users to download them.

I built them as static (SHARED=0 flag when building wxWidgets) so the executable will be completely independent.

**Comment by jmaglic** [comment]
This works for me on Mac. Can we merge and revert the previous merge to include the filesystem header?

**Comment by rlavendomme** [comment]
> 
> 
> This works for me on Mac. Can we merge and revert the previous merge to include the filesystem header?

You mean the filesystem header only or all functions related to filesystem?

In the later case, I would first like to have your opinion on the "compartmentalized file loading and calculation" branch that deal with all potential issues without having to rely on filesystem.

**Comment by jmaglic** [comment]
To conclude: the use of the filesystem library is not necessary right now, but may be used in future since it poses no compilation issue. We use the C++17 standard and WxWidgets 3.1.
