### ISSUE TITLE
Separate GUI control from GUI settings

### ISSUE THREAD

**Issue by jmaglic** [jmaglic/ballpit#39]
### Current status
The function `MainFrame::enableGuiElements(bool)` is used to disable and reenable GUI elements, such as buttons and checkboxes, before and after an event, such as a button press, occurs. The function also determines whether or not a GUI element should be active. For instance, if no valid files have been loaded then the function determines that the calculation button should remain disabled.

### Issue
The check whether or not GUI elements should be disabled is run before and after every action the user takes. This check only has a chance to change, after a new file has been selected. For instance, the "Include HETATM" checkbox is only disabled, when the user selects an `.xyz` file, and the "Calculate" button is only disables after file import has failed.

### Proposed change
Separate the function into two functions. One function disables all GUI elements and reenables all GUI elements that should be reenabled. For this, the status of GUI elements needs to be stored. Importantly, the contained it is stored in, needs to be easily expandable, as new GUI elements may be added. Some sort of map of bools would be ideal, as it allows later addition of elements, and can be accessed by a string key.

The other function updates this map and is only called after loading/ import.

### Improvement
The advantage of dealing with the GUI elements in this fashion is that `MainFrame::enableGuiElements(bool)` only does exactly what its name suggests. Code blocks are not run multiple times, without expecting changes. The structure of the code becomes clearer.

**Comment by rlavendomme** [comment]
The proposed change seems good to me.
I am not sure if a map of bool would be convenient as we would need to define a key for each gui element and make sure to remember the key. One possibility for a good traceability of the keys would be to agree to set something like the ID of each gui element as a string key (e.g. `BUTTON_Browse`, `BUTTON_Calc`, that are nicely listed in base.h ).

**Comment by jmaglic** [comment]
Found a way to make it work with a map that uses object pointers for indexing. This ties the default status directly to the object it disables.
