### ISSUE TITLE
Atom radii aren't imported after atom file selection

### ISSUE THREAD

**Issue by jmaglic** [jmaglic/ballpit#42]
### Description

The problem is related to a recent commit, that changed the behaviour of the file loading upon browse. Right now the program starts with a default radius file path. When an atom file is selected, only the atom file is imported, even though there is a valid radius file path in the respective text box. The user is required to browse a radius file or press the reload button.

### How to reproduce the issue

After start up, browse an atom input file. After a file has been selected, the file will be imported with radii missing.

### Proposed change

After selecting any input file, radius or atom, check whether any input text control is empty. If neither is empty, import both files.

**Comment by rlavendomme** [comment]
The proposed change is simple and should work flawlessly. I don't see any issue in proceeding this way.
